version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/etc:/etc/letsencrypt:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/etc/:/etc/letsencrypt:rw
  redis: 
    image: redis:latest
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - 6379:6379
    restart: always
    volumes:
      - $PWD/redis/data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27016:27017
    restart: always

  mongo-extra:
    image: mongo:latest
    volumes:
      - mongodb-extra:/data/db
      - mongodb-extra_config:/data/configdb
    ports:
      - 27018:27017
    restart: always

volumes:
    mongodb:
    mongodb_config:

    mongodb-extra:
    mongodb-extra_config:
